version: "3.8"

services:
  postgres:
    image: "postgres:15"
    container_name: "tt-postgres"
    environment:
      - POSTGRES_USER=user # CHANEG_ME
      - POSTGRES_PASSWORD=password # CHANGE_ME
      - POSTGRES_DB=db # CHANGE_ME
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
